version: '3.1'

services:

  drupal:
    build: nginx-php7/.
    image: piterpentester/alpine-drupal
    ports:
      - 80:8080
    depends_on:
      - db
    volumes:
      - drupal-modules:/var/www/localhost/htdocs/drupal/modules
      - drupal-profiles:/var/www/localhost/htdocs/drupal/profiles
      - drupal-themes:/var/www/localhost/htdocs/drupal/themes
      - drupal-sites:/var/www/localhost/htdocs/drupal/sites
    networks:
      - drupal-net
    restart: always

  db:
    build: mysql/.
    #image: mariadb
    cap_add:
      - SYS_NICE
    volumes:
      - mysql-data:/var/lib/mysql
    environment:     
      MYSQL_ROOT_PASSWORD: change_me
      #MYSQL_USER: drupal
      #MYSQL_PASSWORD: change_me
      #MYSQL_DATABASE: drupal_db
      #DEFAULT_AUTHENTIFICATION_PLUGIN: mysql_native_password
    networks:
      - drupal-net
    restart: always

networks:
  drupal-net:

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites:
  mysql-data:
